DROP TABLE CALCULATE;

CREATE TABLE CALCULATE
(
    CALCULATE_DATE    DATE NOT NULL,
    PRODUCT_NUM    NUMBER NOT NULL,
    TOTAL_PRICE    NUMBER,
    TOTAL_WEIGHT    NUMBER
);

COMMENT ON COLUMN CALCULATE.CALCULATE_DATE IS '정산일';

COMMENT ON COLUMN CALCULATE.PRODUCT_NUM IS '제품번호';

COMMENT ON COLUMN CALCULATE.TOTAL_PRICE IS '총가격';

COMMENT ON COLUMN CALCULATE.TOTAL_WEIGHT IS '총중량';

COMMENT ON TABLE CALCULATE IS '정산';


DROP TABLE FRUIT;

CREATE TABLE FRUIT
(
    FRUIT_NUM    NUMBER NOT NULL,
    FRUIT_NAME    VARCHAR2(30) NOT NULL,
    FRUIT_PRICE    NUMBER NOT NULL
);

COMMENT ON COLUMN FRUIT.FRUIT_NUM IS '과일번호';

COMMENT ON COLUMN FRUIT.FRUIT_NAME IS '과일명';

COMMENT ON COLUMN FRUIT.FRUIT_PRICE IS '금액(100g)';

COMMENT ON TABLE FRUIT IS '과일';

CREATE UNIQUE INDEX FRUIT_PK ON FRUIT
( FRUIT_NUM );

ALTER TABLE FRUIT
 ADD CONSTRAINT FRUIT_PK PRIMARY KEY ( FRUIT_NUM )
 USING INDEX FRUIT_PK;


DROP TABLE OORDER;

CREATE TABLE OORDER
(
    OORDER_NUM    NUMBER NOT NULL,
    PRODUCT_NUM    NUMBER,
    WEIGHT    NUMBER NOT NULL
);

COMMENT ON COLUMN OORDER.OORDER_NUM IS '주문번호';

COMMENT ON COLUMN OORDER.PRODUCT_NUM IS '제품번호';

COMMENT ON COLUMN OORDER.WEIGHT IS '중량';

COMMENT ON TABLE OORDER IS '주문';

CREATE UNIQUE INDEX OORDER_PK ON OORDER
( OORDER_NUM );

ALTER TABLE OORDER
 ADD CONSTRAINT OORDER_PK PRIMARY KEY ( OORDER_NUM )
 USING INDEX OORDER_PK;


DROP TABLE PAYMENT;

CREATE TABLE PAYMENT
(
    OORDER_NUM    NUMBER NOT NULL,
    TOTAL_PRICE    NUMBER NOT NULL
);

COMMENT ON COLUMN PAYMENT.OORDER_NUM IS '주문번호';

COMMENT ON COLUMN PAYMENT.TOTAL_PRICE IS '총가격';

COMMENT ON TABLE PAYMENT IS '결제';

CREATE UNIQUE INDEX PAYMENT_PK ON PAYMENT
( OORDER_NUM );

ALTER TABLE PAYMENT
 ADD CONSTRAINT PAYMENT_PK PRIMARY KEY ( OORDER_NUM )
 USING INDEX PAYMENT_PK;


DROP TABLE PRODUCT;

CREATE TABLE PRODUCT
(
    PRODUCT_NUM    NUMBER NOT NULL,
    FRUIT_NUM    NUMBER,
    VEG_NUM    NUMBER,
    UNIT    VARCHAR2(20)
);

COMMENT ON COLUMN PRODUCT.PRODUCT_NUM IS '제품번호';

COMMENT ON COLUMN PRODUCT.FRUIT_NUM IS '과일번호';

COMMENT ON COLUMN PRODUCT.VEG_NUM IS '채소번호';

COMMENT ON COLUMN PRODUCT.UNIT IS '단위';

COMMENT ON TABLE PRODUCT IS '제품';

CREATE UNIQUE INDEX PRODUCT_PK ON PRODUCT
( PRODUCT_NUM );

ALTER TABLE PRODUCT
 ADD CONSTRAINT PRODUCT_PK PRIMARY KEY ( PRODUCT_NUM )
 USING INDEX PRODUCT_PK;


DROP TABLE VEGETABLE;

CREATE TABLE VEGETABLE
(
    VEG_NUM    NUMBER NOT NULL,
    VEG_NAME    VARCHAR2(30) NOT NULL,
    VEG_PRICE    NUMBER NOT NULL
);

COMMENT ON COLUMN VEGETABLE.VEG_NUM IS '채소번호';

COMMENT ON COLUMN VEGETABLE.VEG_NAME IS '채소명';

COMMENT ON COLUMN VEGETABLE.VEG_PRICE IS '금액(100g)';

COMMENT ON TABLE VEGETABLE IS '채소';

CREATE UNIQUE INDEX VEGETABLE_PK ON VEGETABLE
( VEG_NUM );

ALTER TABLE VEGETABLE
 ADD CONSTRAINT VEGETABLE_PK PRIMARY KEY ( VEG_NUM )
 USING INDEX VEGETABLE_PK;


DROP TABLE WEIGHT;

CREATE TABLE WEIGHT
(
    UNIT    VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN WEIGHT.UNIT IS '단위';

COMMENT ON TABLE WEIGHT IS '중량';

CREATE UNIQUE INDEX WEIGHT_PK ON WEIGHT
( UNIT );

ALTER TABLE WEIGHT
 ADD CONSTRAINT WEIGHT_PK PRIMARY KEY ( UNIT )
 USING INDEX WEIGHT_PK;


