
--제품
--과일
INSERT INTO PRODUCT(PRODUCT_NUM,FRUIT_NUM,UNIT)
    VALUES(1,1,'G');

INSERT INTO PRODUCT(PRODUCT_NUM,FRUIT_NUM,UNIT)
    VALUES(2,2,'G');

INSERT INTO PRODUCT(PRODUCT_NUM,FRUIT_NUM,UNIT)
    VALUES(3,3,'G');

INSERT INTO PRODUCT(PRODUCT_NUM,FRUIT_NUM,UNIT)
    VALUES(4,4,'G');

--채소
INSERT INTO PRODUCT(PRODUCT_NUM,VEG_NUM,UNIT)
    VALUES(5,1,'G');

INSERT INTO PRODUCT(PRODUCT_NUM,VEG_NUM,UNIT)
    VALUES(6,2,'G');

INSERT INTO PRODUCT(PRODUCT_NUM,VEG_NUM,UNIT)
    VALUES(7,3,'G');

INSERT INTO PRODUCT(PRODUCT_NUM,VEG_NUM,UNIT)
    VALUES(8,4,'G');



--과일
INSERT INTO FRUIT(FRUIT_NUM,FRUIT_NAME,FRUIT_PRICE)
    VALUES(1,'사과',3000);
    
INSERT INTO FRUIT(FRUIT_NUM,FRUIT_NAME,FRUIT_PRICE)
    VALUES(2,'귤',1000);

INSERT INTO FRUIT(FRUIT_NUM,FRUIT_NAME,FRUIT_PRICE)
    VALUES(3,'딸기',4000);

INSERT INTO FRUIT(FRUIT_NUM,FRUIT_NAME,FRUIT_PRICE)
    VALUES(4,'수박',3000);


--채소
INSERT INTO VEGETABLE(VEG_NUM,VEG_NAME,VEG_PRICE)
    VALUES(1,'상추',1000);

INSERT INTO VEGETABLE(VEG_NUM,VEG_NAME,VEG_PRICE)
    VALUES(2,'시금치',1500);

INSERT INTO VEGETABLE(VEG_NUM,VEG_NAME,VEG_PRICE)
    VALUES(3,'배추',2000);

INSERT INTO VEGETABLE(VEG_NUM,VEG_NAME,VEG_PRICE)
    VALUES(4,'방울토마토',3000);


--중량
INSERT INTO WEIGHT(UNIT)
    VALUES('EA');

INSERT INTO WEIGHT(UNIT)
    VALUES('G');

INSERT INTO WEIGHT(UNIT)
    VALUES('KG');



INSERT INTO CALCULATE(CALCULATE_DATE,PRODUCT_NUM,TOTAL_PRICE,TOTAL_WEIGHT)
    VALUES('',0,0,0);





INSERT INTO OORDER(OORDER_NUM,PRODUCT_NUM,WEIGHT)
    VALUES(0,0,0);


INSERT INTO PAYMENT(OORDER_NUM,TOTAL_PRICE)
    VALUES(0,0);









